services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 159263
      POSTGRES_DB: training
    ports:
      - "5432:5432"
    volumes:
      - /Users/intraector/dev/apps/backend/db/postgres/zap:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - db_network

  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: dictdb
      MYSQL_INITDB_SKIP_TZINFO: "1"
    ports:
      - "3306:3306"
    volumes:
      - /Users/intraector/dev/apps/backend/db/mysql/dict:/var/lib/mysql
    restart: unless-stopped

volumes:
  postgres_data:
  mysql_data:

networks:
  db_network: