ktor:
    application:
        modules:
            - dev.ector.ApplicationKt.module
    deployment:
        host: localhost
        port: 8080
    development: true

jwt:
    audience: "ktor-jwt-audience"
    realm: "ktor-jwt-realm"
    issuer: "https://ector.dev"
    secret: $SECRET